import type { Activity } from '@/types';

/**
 * Comprehensive catalog of curated activities for all 20 cities in GlobeTrotter.
 * Provides 6 to 8 activities per destination with realistic start/end times,
 * costs, categories, ratings, descriptions, and high-quality photography
 * to easily build rich 4-day+ itineraries.
 */
export const mockActivities: Activity[] = [
  // ── Tokyo (city-1) ──────────────────────────────────────────────────────────
  {
    id: 'act-tokyo-1',
    name: 'Tsukiji Outer Market Food & Sushi Tasting',
    description: 'Sample freshly sliced bluefin tuna nigiri, tamagoyaki skewers, and wagyu beef skewers.',
    category: 'food',
    time: '08:00',
    startTime: '08:00',
    endTime: '10:00',
    durationHours: 2,
    cost: 45,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1568454537842-d933259bb258?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-1',
  },
  {
    id: 'act-tokyo-2',
    name: 'Senso-ji & Asakusa Historic District Tour',
    description: 'Tokyo oldest Buddhist temple, Nakamise shopping street, and peaceful incense ceremonies.',
    category: 'culture',
    time: '10:30',
    startTime: '10:30',
    endTime: '12:30',
    durationHours: 2,
    cost: 5,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-1',
  },
  {
    id: 'act-tokyo-3',
    name: 'Akihabara Electronics & Anime Wonderland',
    description: 'Explore multi-story retro arcade halls, manga specialty shops, and tech gadget emporiums.',
    category: 'shopping',
    time: '13:30',
    startTime: '13:30',
    endTime: '16:00',
    durationHours: 2.5,
    cost: 20,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    cityId: 'city-1',
  },
  {
    id: 'act-tokyo-4',
    name: 'Meiji Jingu Shrine & Harajuku Fashion Alley',
    description: 'Tranquil forested shrine grounds leading directly into colorful Takeshita Street fashion culture.',
    category: 'sightseeing',
    time: '09:00',
    startTime: '09:00',
    endTime: '11:30',
    durationHours: 2.5,
    cost: 0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-1',
  },
  {
    id: 'act-tokyo-5',
    name: 'teamLab Planets Digital Art Immersion',
    description: 'Walk through water and body-immersive digital light projections in this world-famous museum.',
    category: 'culture',
    time: '14:00',
    startTime: '14:00',
    endTime: '16:30',
    durationHours: 2.5,
    cost: 38,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    cityId: 'city-1',
  },
  {
    id: 'act-tokyo-6',
    name: 'Shibuya Crossing Walk & Sky Deck Sunset',
    description: 'Experience the bustling scramble crossing followed by panoramic 360 views at Shibuya Sky.',
    category: 'sightseeing',
    time: '17:30',
    startTime: '17:30',
    endTime: '19:30',
    durationHours: 2,
    cost: 22,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-1',
  },
  {
    id: 'act-tokyo-7',
    name: 'Shinjuku Omoide Yokocho Yakitori Alley',
    description: 'Smoky lantern-lit alleyways serving grilled chicken skewers, gyoza, and cold draft beer.',
    category: 'nightlife',
    time: '20:00',
    startTime: '20:00',
    endTime: '22:30',
    durationHours: 2.5,
    cost: 35,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-1',
  },

  // ── Paris (city-2) ──────────────────────────────────────────────────────────
  {
    id: 'act-paris-1',
    name: 'Eiffel Tower Summit Skip-the-Line',
    description: 'Ascend to the summit of Paris most iconic monument for panoramic 360-degree views.',
    category: 'sightseeing',
    time: '09:00',
    startTime: '09:00',
    endTime: '11:30',
    durationHours: 2.5,
    cost: 38,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-2',
  },
  {
    id: 'act-paris-2',
    name: 'Louvre Museum Guided Masterpiece Tour',
    description: 'Discover the Mona Lisa, Winged Victory of Samothrace, and thousands of masterworks.',
    category: 'culture',
    time: '12:00',
    startTime: '12:00',
    endTime: '15:30',
    durationHours: 3.5,
    cost: 65,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-2',
  },
  {
    id: 'act-paris-3',
    name: 'Croissant & Macaron Baking Workshop',
    description: 'Hands-on pastry masterclass in Saint-Germain with an artisanal Parisian baker.',
    category: 'food',
    time: '16:00',
    startTime: '16:00',
    endTime: '18:30',
    durationHours: 2.5,
    cost: 85,
    currency: 'USD',
    rating: 4.9,
    cityId: 'city-2',
  },
  {
    id: 'act-paris-4',
    name: 'Seine River Sunset Dinner Cruise',
    description: 'Gourmet 3-course French dining on a glass-canopied boat gliding past illuminated monuments.',
    category: 'sightseeing',
    time: '19:30',
    startTime: '19:30',
    endTime: '22:00',
    durationHours: 2.5,
    cost: 110,
    currency: 'USD',
    rating: 5.0,
    cityId: 'city-2',
  },
  {
    id: 'act-paris-5',
    name: 'Montmartre & Sacré-Cœur Artist Village Walk',
    description: 'Cobblestone hills, street portrait artists at Place du Tertre, and breathtaking church views.',
    category: 'culture',
    time: '09:30',
    startTime: '09:30',
    endTime: '12:00',
    durationHours: 2.5,
    cost: 0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-2',
  },
  {
    id: 'act-paris-6',
    name: 'Palace of Versailles Hall of Mirrors Tour',
    description: 'Explore the lavish Sun King state apartments and expansive musical fountain gardens.',
    category: 'culture',
    time: '13:00',
    startTime: '13:00',
    endTime: '17:30',
    durationHours: 4.5,
    cost: 32,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-2',
  },
  {
    id: 'act-paris-7',
    name: 'Le Marais Vintage Boutiques & Wine Bar Crawl',
    description: 'Browse bohemian boutiques and savor natural wines, duck confit, and artisanal cheeses.',
    category: 'shopping',
    time: '18:30',
    startTime: '18:30',
    endTime: '21:30',
    durationHours: 3,
    cost: 50,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-2',
  },

  // ── Bali (city-3) ───────────────────────────────────────────────────────────
  {
    id: 'act-bali-1',
    name: 'Tegalalang Rice Terrace Sunrise Trek',
    description: 'Hike through emerald green rice paddies with golden rays piercing through morning mist.',
    category: 'adventure',
    time: '06:00',
    startTime: '06:00',
    endTime: '09:00',
    durationHours: 3,
    cost: 15,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-3',
  },
  {
    id: 'act-bali-2',
    name: 'Sacred Monkey Forest Sanctuary Walk',
    description: 'Wander ancient mossy temples and banyan trees inhabited by playful macaque monkeys.',
    category: 'sightseeing',
    time: '10:00',
    startTime: '10:00',
    endTime: '12:30',
    durationHours: 2.5,
    cost: 8,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    cityId: 'city-3',
  },
  {
    id: 'act-bali-3',
    name: 'Traditional Balinese Cooking Class in Ubud',
    description: 'Farm-to-table culinary workshop making sate lilit, lawar salad, and sambal matah.',
    category: 'food',
    time: '13:00',
    startTime: '13:00',
    endTime: '16:00',
    durationHours: 3,
    cost: 35,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-3',
  },
  {
    id: 'act-bali-4',
    name: 'Tanah Lot Sunset Temple Ceremony',
    description: 'Witness the sea temple surrounded by crashing waves during a glowing golden hour.',
    category: 'culture',
    time: '16:30',
    startTime: '16:30',
    endTime: '19:00',
    durationHours: 2.5,
    cost: 5,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-3',
  },
  {
    id: 'act-bali-5',
    name: 'Mount Batur Sunrise Volcano Trek',
    description: 'Early summit hike to watch the sunrise above the clouds with steam-cooked breakfast.',
    category: 'adventure',
    time: '03:30',
    startTime: '03:30',
    endTime: '09:00',
    durationHours: 5.5,
    cost: 50,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-3',
  },
  {
    id: 'act-bali-6',
    name: 'Uluwatu Cliffside Kecak Fire Dance',
    description: 'Hypnotic vocal chanting performance perched on a 70-meter cliff above the roaring surf.',
    category: 'culture',
    time: '18:00',
    startTime: '18:00',
    endTime: '20:00',
    durationHours: 2,
    cost: 15,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    cityId: 'city-3',
  },
  {
    id: 'act-bali-7',
    name: 'Nusa Penida Manta Bay Snorkeling',
    description: 'Speedboat cruise to swim with giant oceanic manta rays in crystal turquoise waters.',
    category: 'adventure',
    time: '08:30',
    startTime: '08:30',
    endTime: '14:30',
    durationHours: 6,
    cost: 75,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-3',
  },

  // ── New York (city-4) ───────────────────────────────────────────────────────
  {
    id: 'act-ny-1',
    name: 'Central Park Full Loop Bike Tour',
    description: 'Cycle 843 acres of paths past Bethesda Terrace, Bow Bridge, and the Reservoir.',
    category: 'adventure',
    time: '09:00',
    startTime: '09:00',
    endTime: '11:30',
    durationHours: 2.5,
    cost: 25,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-4',
  },
  {
    id: 'act-ny-2',
    name: 'The Metropolitan Museum of Art Tour',
    description: 'Explore the Temple of Dendur, European masterworks, and the panoramic rooftop.',
    category: 'culture',
    time: '12:30',
    startTime: '12:30',
    endTime: '15:30',
    durationHours: 3,
    cost: 30,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-4',
  },
  {
    id: 'act-ny-3',
    name: 'High Line Park & Chelsea Market Food Tasting',
    description: 'Walk the elevated freight rail park then savor lobster rolls, tacos, and craft donuts.',
    category: 'food',
    time: '16:00',
    startTime: '16:00',
    endTime: '18:30',
    durationHours: 2.5,
    cost: 40,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-4',
  },
  {
    id: 'act-ny-4',
    name: 'Broadway Musical Evening Performance',
    description: 'Prime orchestra seats to a world-class musical show on the Great White Way.',
    category: 'culture',
    time: '19:30',
    startTime: '19:30',
    endTime: '22:30',
    durationHours: 3,
    cost: 145,
    currency: 'USD',
    rating: 5.0,
    cityId: 'city-4',
  },
  {
    id: 'act-ny-5',
    name: 'Statue of Liberty & Ellis Island Ferry Tour',
    description: 'Cruise New York Harbor and explore the immigration museum and pedestal viewpoint.',
    category: 'sightseeing',
    time: '09:00',
    startTime: '09:00',
    endTime: '12:30',
    durationHours: 3.5,
    cost: 25,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    cityId: 'city-4',
  },
  {
    id: 'act-ny-6',
    name: 'Brooklyn Bridge Walk & DUMBO Pizza Feast',
    description: 'Walk across the iconic suspension bridge and enjoy coal-fired pizza at Grimaldi.',
    category: 'food',
    time: '13:30',
    startTime: '13:30',
    endTime: '16:30',
    durationHours: 3,
    cost: 30,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-4',
  },
  {
    id: 'act-ny-7',
    name: 'Summit One Vanderbilt Night Lights',
    description: 'Immersive mirrored glass observation deck soaring 1,200 feet over Manhattan.',
    category: 'sightseeing',
    time: '20:00',
    startTime: '20:00',
    endTime: '22:00',
    durationHours: 2,
    cost: 48,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-4',
  },

  // ── Barcelona (city-5) ──────────────────────────────────────────────────────
  {
    id: 'act-bcn-1',
    name: 'Sagrada Família Towers & Basilica Tour',
    description: 'Marvel at Gaudí forest of columns and stained glass windows casting rainbow prisms.',
    category: 'culture',
    time: '09:00',
    startTime: '09:00',
    endTime: '11:30',
    durationHours: 2.5,
    cost: 38,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    cityId: 'city-5',
  },
  {
    id: 'act-bcn-2',
    name: 'Park Güell Monumental Zone Walk',
    description: 'Colorful mosaic salamanders, stone viaducts, and panoramic Mediterranean vistas.',
    category: 'sightseeing',
    time: '12:30',
    startTime: '12:30',
    endTime: '15:00',
    durationHours: 2.5,
    cost: 14,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-5',
  },
  {
    id: 'act-bcn-3',
    name: 'La Boqueria Market & Cooking Masterclass',
    description: 'Shop fresh seafood and produce with a chef then cook traditional seafood paella.',
    category: 'food',
    time: '16:00',
    startTime: '16:00',
    endTime: '19:00',
    durationHours: 3,
    cost: 65,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-5',
  },
  {
    id: 'act-bcn-4',
    name: 'Gothic Quarter Evening Tapas & Wine Crawl',
    description: 'Ibérico ham, pimientos de padrón, and cava in historic medieval cobblestone taverns.',
    category: 'food',
    time: '20:00',
    startTime: '20:00',
    endTime: '22:30',
    durationHours: 2.5,
    cost: 50,
    currency: 'USD',
    rating: 4.9,
    cityId: 'city-5',
  },
  {
    id: 'act-bcn-5',
    name: 'Casa Batlló & Casa Milà Modernist Tour',
    description: 'Explore the dragon spine roof and undulating stone balconies along Passeig de Gràcia.',
    category: 'culture',
    time: '10:00',
    startTime: '10:00',
    endTime: '12:30',
    durationHours: 2.5,
    cost: 35,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-5',
  },
  {
    id: 'act-bcn-6',
    name: 'Barceloneta Beach Sunset Paddleboarding',
    description: 'Paddle calm Mediterranean waters followed by chilled sangria at a beachside chiringuito.',
    category: 'adventure',
    time: '17:30',
    startTime: '17:30',
    endTime: '19:30',
    durationHours: 2,
    cost: 28,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    cityId: 'city-5',
  },

  // ── Dubai (city-6) ──────────────────────────────────────────────────────────
  {
    id: 'act-dxb-1',
    name: 'Burj Khalifa Sky Observation Lounge',
    description: 'Ascend to Level 148 atop the world tallest building with Arabic coffee and sweets.',
    category: 'sightseeing',
    time: '09:00',
    startTime: '09:00',
    endTime: '11:00',
    durationHours: 2,
    cost: 110,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-6',
  },
  {
    id: 'act-dxb-2',
    name: 'Dubai Mall & Underwater Zoo Experience',
    description: 'Walk through the 270-degree acrylic aquarium tunnel surrounded by sand tiger sharks.',
    category: 'sightseeing',
    time: '11:30',
    startTime: '11:30',
    endTime: '14:00',
    durationHours: 2.5,
    cost: 40,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    cityId: 'city-6',
  },
  {
    id: 'act-dxb-3',
    name: 'Red Dunes 4x4 Safari & Bedouin BBQ',
    description: 'Dune bashing, sandboarding, camel treks, henna tattoos, and starlit barbecue banquet.',
    category: 'adventure',
    time: '15:00',
    startTime: '15:00',
    endTime: '21:00',
    durationHours: 6,
    cost: 85,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-6',
  },
  {
    id: 'act-dxb-4',
    name: 'Old Dubai Abra Boat & Spice Souk Walk',
    description: 'Ride a wooden abra boat across Dubai Creek to explore fragrant frankincense and gold.',
    category: 'shopping',
    time: '09:30',
    startTime: '09:30',
    endTime: '12:30',
    durationHours: 3,
    cost: 15,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-6',
  },
  {
    id: 'act-dxb-5',
    name: 'Dubai Marina Luxury Yacht Sunset Cruise',
    description: 'Sail past Bluewaters Island and Ain Dubai with refreshing canapés and skyline views.',
    category: 'sightseeing',
    time: '17:00',
    startTime: '17:00',
    endTime: '19:30',
    durationHours: 2.5,
    cost: 65,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-6',
  },

  // ── Amsterdam (city-7) ──────────────────────────────────────────────────────
  {
    id: 'act-ams-1',
    name: 'Rijksmuseum Golden Age Masterpieces',
    description: 'Guided viewing of Rembrandt Night Watch and Vermeer intimate domestic scenes.',
    category: 'culture',
    time: '09:00',
    startTime: '09:00',
    endTime: '12:00',
    durationHours: 3,
    cost: 26,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-7',
  },
  {
    id: 'act-ams-2',
    name: 'Van Gogh Museum Life & Art Tour',
    description: 'World largest collection of Vincent van Gogh paintings, sketches, and personal letters.',
    category: 'culture',
    time: '13:00',
    startTime: '13:00',
    endTime: '15:30',
    durationHours: 2.5,
    cost: 24,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-7',
  },
  {
    id: 'act-ams-3',
    name: 'Jordaan Canal Ring Evening Cruise & Drinks',
    description: 'Open-boat canal tour with Dutch cheeses, bitterballen, and craft beers at sunset.',
    category: 'sightseeing',
    time: '17:00',
    startTime: '17:00',
    endTime: '19:00',
    durationHours: 2,
    cost: 32,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-7',
  },
  {
    id: 'act-ams-4',
    name: 'Vondelpark & Museumplein Bike Ride',
    description: 'Pedal like a local through Amsterdam most famous park and stopping for warm poffertjes.',
    category: 'adventure',
    time: '10:00',
    startTime: '10:00',
    endTime: '12:30',
    durationHours: 2.5,
    cost: 15,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    cityId: 'city-7',
  },
  {
    id: 'act-ams-5',
    name: 'Anne Frank House Historical Visit',
    description: 'Reflective and moving audio tour of the secret annex preserved in the Jordaan district.',
    category: 'culture',
    time: '14:30',
    startTime: '14:30',
    endTime: '16:30',
    durationHours: 2,
    cost: 18,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-7',
  },

  // ── Rome (city-9) ───────────────────────────────────────────────────────────
  {
    id: 'act-rom-1',
    name: 'Colosseum & Roman Forum VIP Tour',
    description: 'Gladiator arena floor access followed by Julius Caesar temple ruins in the Forum.',
    category: 'culture',
    time: '08:30',
    startTime: '08:30',
    endTime: '12:00',
    durationHours: 3.5,
    cost: 48,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-9',
  },
  {
    id: 'act-rom-2',
    name: 'Trastevere Handmade Pasta & Gelato Tour',
    description: 'Taste authentic carbonara, cacio e pepe, supplì, and artisanal pistachio gelato.',
    category: 'food',
    time: '12:30',
    startTime: '12:30',
    endTime: '15:00',
    durationHours: 2.5,
    cost: 55,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-9',
  },
  {
    id: 'act-rom-3',
    name: 'Vatican Museums & Sistine Chapel Tour',
    description: 'Admire Michelangelo ceiling frescoes and Raphael Rooms with early skip-the-line entry.',
    category: 'culture',
    time: '15:30',
    startTime: '15:30',
    endTime: '18:30',
    durationHours: 3,
    cost: 52,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    cityId: 'city-9',
  },
  {
    id: 'act-rom-4',
    name: 'Pantheon & Trevi Fountain Twilight Stroll',
    description: 'Toss a coin into the Trevi Fountain and gaze up through the ancient oculus dome.',
    category: 'sightseeing',
    time: '19:30',
    startTime: '19:30',
    endTime: '21:30',
    durationHours: 2,
    cost: 5,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-9',
  },
  {
    id: 'act-rom-5',
    name: 'Borghese Gallery & Gardens Tour',
    description: 'Sculptures by Bernini and paintings by Caravaggio in a 17th-century princely villa.',
    category: 'culture',
    time: '10:00',
    startTime: '10:00',
    endTime: '12:30',
    durationHours: 2.5,
    cost: 28,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-9',
  },

  // ── Sydney (city-10) ────────────────────────────────────────────────────────
  {
    id: 'act-syd-1',
    name: 'Sydney Harbour BridgeClimb Dawn Walk',
    description: 'Scale the steel summit 134 meters above the harbor for breathtaking sunrise views.',
    category: 'adventure',
    time: '06:00',
    startTime: '06:00',
    endTime: '09:30',
    durationHours: 3.5,
    cost: 195,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    cityId: 'city-10',
  },
  {
    id: 'act-syd-2',
    name: 'Sydney Opera House Behind-the-Scenes Tour',
    description: 'Explore the concert halls and architectural feats beneath the iconic ceramic sails.',
    category: 'culture',
    time: '10:30',
    startTime: '10:30',
    endTime: '12:30',
    durationHours: 2,
    cost: 42,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-10',
  },
  {
    id: 'act-syd-3',
    name: 'Bondi to Coogee Coastal Cliff Walk',
    description: 'Stroll scenic coastal headlands with turquoise waves and seaside rock pools.',
    category: 'sightseeing',
    time: '14:00',
    startTime: '14:00',
    endTime: '17:00',
    durationHours: 3,
    cost: 0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-10',
  },
  {
    id: 'act-syd-4',
    name: 'Manly Beach Ferry & Fish and Chips',
    description: 'Scenic 30-minute ferry across Sydney Harbour followed by beachside dining.',
    category: 'food',
    time: '17:30',
    startTime: '17:30',
    endTime: '20:30',
    durationHours: 3,
    cost: 25,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    cityId: 'city-10',
  },

  // ── Kyoto (city-11) ─────────────────────────────────────────────────────────
  {
    id: 'act-kyo-1',
    name: 'Fushimi Inari 10,000 Torii Gates Hike',
    description: 'Hike through vermilion torii paths winding up sacred mountain trails at sunrise.',
    category: 'adventure',
    time: '06:30',
    startTime: '06:30',
    endTime: '09:30',
    durationHours: 3,
    cost: 0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-11',
  },
  {
    id: 'act-kyo-2',
    name: 'Kinkaku-ji (Golden Pavilion) Zen Tour',
    description: 'Gaze upon the glittering three-story gold temple reflected on Mirror Pond.',
    category: 'culture',
    time: '10:30',
    startTime: '10:30',
    endTime: '12:30',
    durationHours: 2,
    cost: 5,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-11',
  },
  {
    id: 'act-kyo-3',
    name: 'Arashiyama Bamboo Forest & Tenryu-ji',
    description: 'Towering bamboo stalks singing in the breeze and ancient 14th-century pond gardens.',
    category: 'sightseeing',
    time: '13:30',
    startTime: '13:30',
    endTime: '16:00',
    durationHours: 2.5,
    cost: 6,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-11',
  },
  {
    id: 'act-kyo-4',
    name: 'Gion Traditional Kaiseki Multi-Course Feast',
    description: 'Exquisite multi-course Kyoto banquet prepared with seasonal delicate ingredients.',
    category: 'food',
    time: '18:30',
    startTime: '18:30',
    endTime: '21:00',
    durationHours: 2.5,
    cost: 110,
    currency: 'USD',
    rating: 5.0,
    cityId: 'city-11',
  },

  // ── London (city-12) ────────────────────────────────────────────────────────
  {
    id: 'act-ldn-1',
    name: 'Tower of London & Crown Jewels Tour',
    description: 'Discover 1,000 years of royal history and the world most priceless diamonds.',
    category: 'culture',
    time: '09:00',
    startTime: '09:00',
    endTime: '11:45',
    durationHours: 2.75,
    cost: 38,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-12',
  },
  {
    id: 'act-ldn-2',
    name: 'Borough Market Artisan Gourmet Crawl',
    description: 'Sample British artisan cheeses, duck confit sandwiches, and fresh Scottish oysters.',
    category: 'food',
    time: '12:15',
    startTime: '12:15',
    endTime: '14:30',
    durationHours: 2.25,
    cost: 35,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-12',
  },
  {
    id: 'act-ldn-3',
    name: 'British Museum Ancient Antiquities Tour',
    description: 'Marvel at the Rosetta Stone, Parthenon Sculptures, and Egyptian mummies.',
    category: 'culture',
    time: '15:00',
    startTime: '15:00',
    endTime: '18:00',
    durationHours: 3,
    cost: 0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-12',
  },
  {
    id: 'act-ldn-4',
    name: 'West End Musical Evening Performance',
    description: 'Top-tier theatrical drama and award-winning musical in London historic theatreland.',
    category: 'culture',
    time: '19:30',
    startTime: '19:30',
    endTime: '22:15',
    durationHours: 2.75,
    cost: 110,
    currency: 'USD',
    rating: 5.0,
    cityId: 'city-12',
  },

  // ── Santorini (city-13) ─────────────────────────────────────────────────────
  {
    id: 'act-san-1',
    name: 'Fira to Oia Caldera Cliffside Hike',
    description: 'Iconic 10km coastal trek with panoramic views over the volcanic caldera and white churches.',
    category: 'adventure',
    time: '07:30',
    startTime: '07:30',
    endTime: '11:00',
    durationHours: 3.5,
    cost: 0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-13',
  },
  {
    id: 'act-san-2',
    name: 'Volcanic Island & Hot Springs Catamaran Cruise',
    description: 'Sail to the volcano crater, swim in warm sulfur springs, and enjoy Greek grilled souvlaki.',
    category: 'sightseeing',
    time: '14:30',
    startTime: '14:30',
    endTime: '19:30',
    durationHours: 5,
    cost: 125,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    cityId: 'city-13',
  },
  {
    id: 'act-san-3',
    name: 'Santorini Wine Tasting & Cliffside Winery Tour',
    description: 'Sample crisp Assyrtiko volcanic wines paired with graviera cheese at sunset.',
    category: 'food',
    time: '17:00',
    startTime: '17:00',
    endTime: '19:30',
    durationHours: 2.5,
    cost: 65,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-13',
  },
  {
    id: 'act-san-4',
    name: 'Red Beach & Akrotiri Bronze Age Ruins',
    description: 'Explore the preserved prehistoric town buried in volcanic ash 3,600 years ago.',
    category: 'culture',
    time: '10:00',
    startTime: '10:00',
    endTime: '13:00',
    durationHours: 3,
    cost: 20,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-13',
  },

  // ── Cape Town (city-14) ─────────────────────────────────────────────────────
  {
    id: 'act-cpt-1',
    name: 'Table Mountain Rotating Cableway',
    description: '360-degree rotating cable car ascending to the flat summit overlooking Camps Bay.',
    category: 'adventure',
    time: '09:00',
    startTime: '09:00',
    endTime: '12:00',
    durationHours: 3,
    cost: 32,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-14',
  },
  {
    id: 'act-cpt-2',
    name: 'Boulders Beach African Penguin Sanctuary',
    description: 'Walk sandy boardwalks among hundreds of wild African penguins swimming and nesting.',
    category: 'sightseeing',
    time: '13:30',
    startTime: '13:30',
    endTime: '16:00',
    durationHours: 2.5,
    cost: 15,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-14',
  },
  {
    id: 'act-cpt-3',
    name: 'Cape Point & Cape of Good Hope Day Safari',
    description: 'Drive Chapman Peak to the rugged southwestern tip of the African continent.',
    category: 'adventure',
    time: '08:30',
    startTime: '08:30',
    endTime: '14:30',
    durationHours: 6,
    cost: 75,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-14',
  },
  {
    id: 'act-cpt-4',
    name: 'V&A Waterfront Seafood & Marimba Dinner',
    description: 'Fresh grilled kingklip and calamari accompanied by live African acoustic percussion.',
    category: 'food',
    time: '18:30',
    startTime: '18:30',
    endTime: '21:00',
    durationHours: 2.5,
    cost: 45,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-14',
  },

  // ── Prague (city-15) ────────────────────────────────────────────────────────
  {
    id: 'act-prg-1',
    name: 'Charles Bridge Dawn Walk & Old Town Square',
    description: 'Empty cobblestones and Gothic statues at dawn followed by the Astronomical Clock.',
    category: 'sightseeing',
    time: '07:30',
    startTime: '07:30',
    endTime: '10:00',
    durationHours: 2.5,
    cost: 0,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-15',
  },
  {
    id: 'act-prg-2',
    name: 'Prague Castle Complex & St. Vitus Cathedral',
    description: 'Explore the royal courtyards, Gothic gargoyles, and vibrant Golden Lane.',
    category: 'culture',
    time: '10:30',
    startTime: '10:30',
    endTime: '14:00',
    durationHours: 3.5,
    cost: 20,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-15',
  },
  {
    id: 'act-prg-3',
    name: 'Traditional Czech Brewery & Goulash Feast',
    description: 'Hearty beef goulash with bread dumplings and freshly tapped unpasteurized Pilsner.',
    category: 'food',
    time: '18:00',
    startTime: '18:00',
    endTime: '20:30',
    durationHours: 2.5,
    cost: 30,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-15',
  },
  {
    id: 'act-prg-4',
    name: 'Vltava River Wooden Riverboat Cruise',
    description: 'Glide beneath Charles Bridge with live jazz and illuminated views of the castle.',
    category: 'sightseeing',
    time: '21:00',
    startTime: '21:00',
    endTime: '22:30',
    durationHours: 1.5,
    cost: 22,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    cityId: 'city-15',
  },

  // ── Singapore (city-16) ─────────────────────────────────────────────────────
  {
    id: 'act-sg-1',
    name: 'Gardens by the Bay Supertrees & Cloud Forest',
    description: 'Walk the aerial skyway between giant vertical gardens and indoor mountain waterfall.',
    category: 'sightseeing',
    time: '09:00',
    startTime: '09:00',
    endTime: '12:00',
    durationHours: 3,
    cost: 32,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-16',
  },
  {
    id: 'act-sg-2',
    name: 'Lau Pa Sat Satay & Michelin Hawker Crawl',
    description: 'Sample laksa, chili crab buns, chicken rice, and charcoal grilled satay skewers.',
    category: 'food',
    time: '12:30',
    startTime: '12:30',
    endTime: '14:30',
    durationHours: 2,
    cost: 22,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-16',
  },
  {
    id: 'act-sg-3',
    name: 'Singapore Night Safari Tram Tour',
    description: 'World first nocturnal wildlife park with open-air trams through rainforest habitats.',
    category: 'adventure',
    time: '19:30',
    startTime: '19:30',
    endTime: '22:30',
    durationHours: 3,
    cost: 45,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-16',
  },
  {
    id: 'act-sg-4',
    name: 'Sentosa Island Cable Car & Beach Club',
    description: 'Ride the panoramic harbor cable car to Siloso beach for infinity pool cocktails.',
    category: 'adventure',
    time: '15:00',
    startTime: '15:00',
    endTime: '18:30',
    durationHours: 3.5,
    cost: 40,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    cityId: 'city-16',
  },

  // ── Istanbul (city-17) ──────────────────────────────────────────────────────
  {
    id: 'act-ist-1',
    name: 'Hagia Sophia & Blue Mosque Architecture',
    description: 'Stand under the colossal 6th-century dome and blue Iznik ceramic tile galleries.',
    category: 'culture',
    time: '09:00',
    startTime: '09:00',
    endTime: '12:00',
    durationHours: 3,
    cost: 28,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-17',
  },
  {
    id: 'act-ist-2',
    name: 'Grand Bazaar & Spice Market Tasting Walk',
    description: 'Browse artisan lanterns, Turkish carpets, saffron spices, and fresh pistachio baklava.',
    category: 'shopping',
    time: '13:00',
    startTime: '13:00',
    endTime: '15:30',
    durationHours: 2.5,
    cost: 20,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-17',
  },
  {
    id: 'act-ist-3',
    name: 'Bosphorus Sunset Yacht Cruise with Meze',
    description: 'Sail between Europe and Asia past illuminated palaces with Turkish tea and meze.',
    category: 'sightseeing',
    time: '17:00',
    startTime: '17:00',
    endTime: '19:30',
    durationHours: 2.5,
    cost: 35,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-17',
  },
  {
    id: 'act-ist-4',
    name: 'Traditional Turkish Hamam & Massage',
    description: 'Centuries-old marble bathhouse scrub, foam wash, and eucalyptus oil massage.',
    category: 'wellness',
    time: '20:00',
    startTime: '20:00',
    endTime: '22:00',
    durationHours: 2,
    cost: 60,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-17',
  },

  // ── Bangkok (city-8) ────────────────────────────────────────────────────────
  {
    id: 'act-bgk-1',
    name: 'Grand Palace & Wat Phra Kaew Royal Tour',
    description: 'Explore the golden spires, Thai murals, and the revered Emerald Buddha.',
    category: 'culture',
    time: '09:00',
    startTime: '09:00',
    endTime: '12:00',
    durationHours: 3,
    cost: 16,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-8',
  },
  {
    id: 'act-bgk-2',
    name: 'Damnoen Saduak Floating Market Longtail Boat',
    description: 'Navigate vibrant canal waterways with vendors selling pad thai, mango sticky rice, and fresh coconut.',
    category: 'food',
    time: '13:00',
    startTime: '13:00',
    endTime: '15:30',
    durationHours: 2.5,
    cost: 25,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-8',
  },
  {
    id: 'act-bgk-3',
    name: 'Wat Arun (Temple of Dawn) Sunset Climb',
    description: 'Admire porcelain mosaic pagodas on the Chao Phraya River bank during twilight.',
    category: 'sightseeing',
    time: '16:30',
    startTime: '16:30',
    endTime: '18:30',
    durationHours: 2,
    cost: 5,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-8',
  },
  {
    id: 'act-bgk-4',
    name: 'Chinatown (Yaowarat) Street Food Crawl',
    description: 'Michelin-guide street food stalls serving crab fried rice, satay, and crispy oyster omelets.',
    category: 'food',
    time: '19:30',
    startTime: '19:30',
    endTime: '22:00',
    durationHours: 2.5,
    cost: 20,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    cityId: 'city-8',
  },
  {
    id: 'act-bgk-5',
    name: 'Chatuchak Weekend Market Shopping Spree',
    description: '15,000 stalls of vintage clothing, handmade ceramics, artisanal soaps, and Thai silk.',
    category: 'shopping',
    time: '10:00',
    startTime: '10:00',
    endTime: '13:30',
    durationHours: 3.5,
    cost: 30,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    cityId: 'city-8',
  },
  {
    id: 'act-bgk-6',
    name: 'Rooftop Sky Bar Cocktail Evening at King Power Mahanakhon',
    description: 'Glass-floor skywalk 314 meters high with panoramic 360-degree views over Bangkok.',
    category: 'nightlife',
    time: '20:30',
    startTime: '20:30',
    endTime: '23:00',
    durationHours: 2.5,
    cost: 45,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-8',
  },

  // ── Lisbon (city-18) ────────────────────────────────────────────────────────
  {
    id: 'act-lis-1',
    name: 'Belém Tower & Jerónimos Monastery Tour',
    description: 'Manueline architectural masterpieces on the Tagus river and original warm pastel de nata.',
    category: 'culture',
    time: '09:00',
    startTime: '09:00',
    endTime: '12:00',
    durationHours: 3,
    cost: 18,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-18',
  },
  {
    id: 'act-lis-2',
    name: 'Time Out Market Gourmet Portuguese Tasting',
    description: 'Top Lisbon chefs under one historic roof serving bacalhau, garlic shrimp, and artisanal cheeses.',
    category: 'food',
    time: '12:30',
    startTime: '12:30',
    endTime: '14:30',
    durationHours: 2,
    cost: 30,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-18',
  },
  {
    id: 'act-lis-3',
    name: 'Alfama Historic Tram 28 & Castle Walk',
    description: 'Ride vintage yellow tram through steep winding alleys up to São Jorge Castle panoramic viewpoint.',
    category: 'sightseeing',
    time: '15:00',
    startTime: '15:00',
    endTime: '17:30',
    durationHours: 2.5,
    cost: 12,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-18',
  },
  {
    id: 'act-lis-4',
    name: 'Authentic Fado Music & Wine Evening',
    description: 'Haunting Portuguese soulful guitar melodies with grilled sardines and regional Alentejo wine.',
    category: 'culture',
    time: '20:00',
    startTime: '20:00',
    endTime: '22:30',
    durationHours: 2.5,
    cost: 45,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-18',
  },
  {
    id: 'act-lis-5',
    name: 'Sintra Fairytale Palace & Quinta da Regaleira',
    description: 'Day trip exploring the vivid yellow Pena Palace and the mystic subterranean initiation well.',
    category: 'adventure',
    time: '09:30',
    startTime: '09:30',
    endTime: '15:30',
    durationHours: 6,
    cost: 40,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    cityId: 'city-18',
  },

  // ── Rio de Janeiro (city-19) ────────────────────────────────────────────────
  {
    id: 'act-rio-1',
    name: 'Christ the Redeemer & Corcovado Train',
    description: 'Cog train through Tijuca rainforest to the 30-meter statue overlooking the entire Guanabara Bay.',
    category: 'sightseeing',
    time: '08:30',
    startTime: '08:30',
    endTime: '11:30',
    durationHours: 3,
    cost: 25,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    cityId: 'city-19',
  },
  {
    id: 'act-rio-2',
    name: 'Copacabana & Ipanema Beachside Caipirinha Crawl',
    description: 'Stroll the wave-patterned boardwalks with fresh coconut water and grilled cheese skewers.',
    category: 'food',
    time: '12:30',
    startTime: '12:30',
    endTime: '15:00',
    durationHours: 2.5,
    cost: 20,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    cityId: 'city-19',
  },
  {
    id: 'act-rio-3',
    name: 'Sugarloaf Mountain Cable Car Sunset',
    description: 'Two-stage glass cable car ascent to Morro da Urca for the most famous sunset in South America.',
    category: 'adventure',
    time: '16:30',
    startTime: '16:30',
    endTime: '19:00',
    durationHours: 2.5,
    cost: 32,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-19',
  },
  {
    id: 'act-rio-4',
    name: 'Lapa Arches & Selarón Ceramic Steps Samba Night',
    description: 'Walk the 215 colorful mosaic tile stairs then enjoy live samba rhythms in historic clubs.',
    category: 'nightlife',
    time: '20:00',
    startTime: '20:00',
    endTime: '23:00',
    durationHours: 3,
    cost: 25,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-19',
  },

  // ── Maldives (city-20) ──────────────────────────────────────────────────────
  {
    id: 'act-mld-1',
    name: 'House Reef Guided Coral & Turtle Snorkel',
    description: 'Swim in crystal translucent lagoons alongside sea turtles and harmless reef sharks.',
    category: 'adventure',
    time: '08:30',
    startTime: '08:30',
    endTime: '11:00',
    durationHours: 2.5,
    cost: 65,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    cityId: 'city-20',
  },
  {
    id: 'act-mld-2',
    name: 'Sandbank Private Island Picnic',
    description: 'Speedboat transfer to an uninhabited white sand spit with chilled fresh fruit and coconuts.',
    category: 'sightseeing',
    time: '12:00',
    startTime: '12:00',
    endTime: '15:00',
    durationHours: 3,
    cost: 120,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-20',
  },
  {
    id: 'act-mld-3',
    name: 'Overwater Sunset Dolphin Watching Cruise',
    description: 'Traditional wooden dhoni cruise watching spinner dolphins jumping in the evening sun.',
    category: 'sightseeing',
    time: '16:30',
    startTime: '16:30',
    endTime: '18:45',
    durationHours: 2.25,
    cost: 85,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-20',
  },
  {
    id: 'act-mld-4',
    name: 'Submerged Underwater Glass Restaurant Dining',
    description: 'Fine dining 5 meters below sea level with 180-degree panoramic views of living coral reefs.',
    category: 'food',
    time: '19:30',
    startTime: '19:30',
    endTime: '22:00',
    durationHours: 2.5,
    cost: 220,
    currency: 'USD',
    rating: 5.0,
    cityId: 'city-20',
  },
  {
    id: 'act-mld-5',
    name: 'Whale Shark Safari & Deep Lagoon Snorkel',
    description: 'South Ari Atoll marine sanctuary cruise to swim alongside gentle ocean whale sharks.',
    category: 'adventure',
    time: '08:00',
    startTime: '08:00',
    endTime: '13:00',
    durationHours: 5,
    cost: 160,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    cityId: 'city-20',
  },
  {
    id: 'act-mld-6',
    name: 'Overwater Luxury Spa & Coconut Body Polish',
    description: 'Glass-floor treatment pavilion over the lagoon with tropical botanical oils and massage.',
    category: 'wellness',
    time: '14:30',
    startTime: '14:30',
    endTime: '16:30',
    durationHours: 2,
    cost: 140,
    currency: 'USD',
    imageUrl: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    cityId: 'city-20',
  },
];
