import type { Trip } from '@/types';

/**
 * Seed dataset of 8 highly detailed, realistic trip objects for GlobeTrotter.
 * - Dates: Strictly between September 2026 and December 2027 (no past dates).
 * - Chronological Order: Activities within each stop are strictly sorted by startTime.
 * - Theme: Premium Minimalist, verified Unsplash photography.
 */
export const mockTrips: Trip[] = [
  // ── Trip 1: Golden Autumn in Japan ──────────────────────────────────────────
  {
    id: 'trip-101',
    name: 'Golden Autumn in Japan',
    description: 'Immerse in Tokyo modern energy, Kyoto ancient shrine foliage, and Dotonbori culinary mastery.',
    coverPhoto: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    budget: 4200,
    budgetBreakdown: { transport: 950, stay: 1600, activities: 750, meals: 600, misc: 300 },
    isPublic: true,
    status: 'upcoming',
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-22T12:00:00Z',
    userId: 'user-1',
    shareSlug: 'golden-autumn-japan-2026',
    tags: ['culture', 'food', 'sightseeing'],
    stops: [
      {
        id: 'stop-101-a',
        cityId: 'city-1',
        city: 'Tokyo',
        country: 'Japan',
        countryCode: 'JP',
        startDate: '2026-10-10',
        endDate: '2026-10-15',
        order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-101-1',
            name: 'Tsukiji Outer Market Gourmet Breakfast',
            description: 'Sample fresh Otoro nigiri, tamagoyaki skewers, and freshly shucked oysters.',
            category: 'food',
            startTime: '08:00',
            endTime: '10:00',
            durationHours: 2,
            cost: 45,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-1',
            imageUrl: 'https://images.unsplash.com/photo-1568454537842-d933259bb258?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-101-2',
            name: 'Senso-ji & Asakusa Historic Walk',
            description: 'Explore Tokyo oldest Buddhist temple and browse traditional crafts along Nakamise-dori.',
            category: 'culture',
            startTime: '10:30',
            endTime: '13:00',
            durationHours: 2.5,
            cost: 10,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-1',
            imageUrl: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-101-3',
            name: 'Meiji Jingu Shrine & Harajuku Discovery',
            description: 'Stroll through the serene evergreen forest surrounding Meiji Shrine before exploring Takeshita Street.',
            category: 'sightseeing',
            startTime: '14:30',
            endTime: '17:00',
            durationHours: 2.5,
            cost: 0,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-1',
            imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-101-4',
            name: 'Shibuya Crossing & Sky Sunset View',
            description: 'Experience the 360-degree open-air observation deck atop Shibuya Scramble Square at golden hour.',
            category: 'sightseeing',
            startTime: '17:30',
            endTime: '19:30',
            durationHours: 2,
            cost: 22,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-1',
            imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
      {
        id: 'stop-101-b',
        cityId: 'city-11',
        city: 'Kyoto',
        country: 'Japan',
        countryCode: 'JP',
        startDate: '2026-10-15',
        endDate: '2026-10-19',
        order: 1,
        coverPhoto: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-101-5',
            name: 'Fushimi Inari Torii Gate Sunrise Trek',
            description: 'Early morning climb through thousands of vermilion torii gates winding up sacred Mount Inari.',
            category: 'adventure',
            startTime: '06:30',
            endTime: '09:30',
            durationHours: 3,
            cost: 0,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-11',
            imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-101-6',
            name: 'Kinkaku-ji (Golden Pavilion) Visit',
            description: 'Admire the Zen Buddhist temple with its top two floors completely covered in pure gold leaf.',
            category: 'culture',
            startTime: '11:00',
            endTime: '12:45',
            durationHours: 1.75,
            cost: 5,
            currency: 'USD',
            rating: 4.7,
            cityId: 'city-11',
            imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-101-7',
            name: 'Arashiyama Bamboo Grove & Tenryu-ji',
            description: 'Wander the towering green bamboo pathways and UNESCO World Heritage zen garden.',
            category: 'sightseeing',
            startTime: '14:00',
            endTime: '16:30',
            durationHours: 2.5,
            cost: 6,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-11',
            imageUrl: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-101-8',
            name: 'Gion Traditional Kaiseki Dinner',
            description: 'Multi-course seasonal Kyoto banquet served in a private tatami room overlooking a lantern-lit garden.',
            category: 'food',
            startTime: '19:00',
            endTime: '21:30',
            durationHours: 2.5,
            cost: 110,
            currency: 'USD',
            rating: 5.0,
            cityId: 'city-11',
            imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
    ],
  },

  // ── Trip 2: Mediterranean Grand Tour ───────────────────────────────────────
  {
    id: 'trip-102',
    name: 'Mediterranean Grand Tour',
    description: 'Sun-drenched coasts, classical antiquities, modernist architecture, and Aegean sunsets.',
    coverPhoto: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
    budget: 5400,
    budgetBreakdown: { transport: 1200, stay: 2100, activities: 950, meals: 850, misc: 300 },
    isPublic: true,
    status: 'upcoming',
    createdAt: '2026-08-15T09:00:00Z',
    updatedAt: '2026-08-21T14:30:00Z',
    userId: 'user-1',
    shareSlug: 'mediterranean-grand-tour-2026',
    tags: ['sightseeing', 'culture', 'beach'],
    stops: [
      {
        id: 'stop-102-a',
        cityId: 'city-9',
        city: 'Rome',
        country: 'Italy',
        countryCode: 'IT',
        startDate: '2026-09-12',
        endDate: '2026-09-16',
        order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-102-1',
            name: 'Colosseum & Roman Forum VIP Access',
            description: 'Walk the arena floor of the ancient amphitheater and explore Caesar palace ruins on Palatine Hill.',
            category: 'culture',
            startTime: '08:30',
            endTime: '12:00',
            durationHours: 3.5,
            cost: 48,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-9',
            imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-102-2',
            name: 'Trastevere Pasta & Wine Tasting Tour',
            description: 'Handmade cacio e pepe, supplì, and regional Lazio wines in Rome most picturesque cobblestone quarter.',
            category: 'food',
            startTime: '13:00',
            endTime: '15:30',
            durationHours: 2.5,
            cost: 65,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-9',
            imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-102-3',
            name: 'Vatican Museums & Sistine Chapel Tour',
            description: 'Afternoon guided exploration through Renaissance galleries culminating at Michelangelo masterwork ceiling.',
            category: 'culture',
            startTime: '16:00',
            endTime: '19:00',
            durationHours: 3,
            cost: 55,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-9',
            imageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
      {
        id: 'stop-102-b',
        cityId: 'city-13',
        city: 'Santorini',
        country: 'Greece',
        countryCode: 'GR',
        startDate: '2026-09-16',
        endDate: '2026-09-20',
        order: 1,
        coverPhoto: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-102-4',
            name: 'Fira to Oia Caldera Cliff Hike',
            description: 'Panoramic 10km coastal trek along the edge of the volcanic crater overlooking the sapphire Aegean Sea.',
            category: 'adventure',
            startTime: '07:30',
            endTime: '11:00',
            durationHours: 3.5,
            cost: 0,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-13',
            imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-102-5',
            name: 'Volcanic Island & Hot Springs Catamaran Cruise',
            description: 'Sail to Nea Kameni volcano, swim in geothermal sulfur springs, and enjoy freshly grilled Greek BBQ on board.',
            category: 'sightseeing',
            startTime: '14:30',
            endTime: '19:30',
            durationHours: 5,
            cost: 125,
            currency: 'USD',
            rating: 5.0,
            cityId: 'city-13',
            imageUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
    ],
  },

  // ── Trip 3: Nordic Lights & Arctic Fjords ──────────────────────────────────
  {
    id: 'trip-103',
    name: 'Nordic Lights & Arctic Fjords',
    description: 'Chasing aurora borealis across snow-covered peaks, reindeer sledding, and cozy Scandinavian design.',
    coverPhoto: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=1200&q=80',
    budget: 3800,
    budgetBreakdown: { transport: 900, stay: 1450, activities: 850, meals: 450, misc: 150 },
    isPublic: true,
    status: 'upcoming',
    createdAt: '2026-08-18T11:00:00Z',
    updatedAt: '2026-08-22T08:00:00Z',
    userId: 'user-1',
    shareSlug: 'nordic-lights-fjords-2026',
    tags: ['adventure', 'winter', 'nature'],
    stops: [
      {
        id: 'stop-103-a',
        cityId: 'city-7',
        city: 'Amsterdam',
        country: 'Netherlands',
        countryCode: 'NL',
        startDate: '2026-11-12',
        endDate: '2026-11-16',
        order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-103-1',
            name: 'Historic Canal Ring Morning Cruise',
            description: 'Gliding along the 17th-century UNESCO canal belt with barista coffee and warm Dutch stroopwafels.',
            category: 'sightseeing',
            startTime: '09:00',
            endTime: '10:30',
            durationHours: 1.5,
            cost: 24,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-7',
            imageUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-103-2',
            name: 'Rijksmuseum Golden Age Masterpieces',
            description: 'Curated tour featuring Rembrandt The Night Watch, Vermeer The Milkmaid, and antique maritime halls.',
            category: 'culture',
            startTime: '11:30',
            endTime: '14:30',
            durationHours: 3,
            cost: 28,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-7',
            imageUrl: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-103-3',
            name: 'Jordaan Craft Cheese & Bitterballen Crawl',
            description: 'Tasting aged Gouda, truffle Edam, local microbrews, and crispy bitterballen in a cozy bruin café.',
            category: 'food',
            startTime: '17:00',
            endTime: '19:30',
            durationHours: 2.5,
            cost: 50,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-7',
            imageUrl: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
      {
        id: 'stop-103-b',
        cityId: 'city-15',
        city: 'Prague',
        country: 'Czech Republic',
        countryCode: 'CZ',
        startDate: '2026-11-16',
        endDate: '2026-11-20',
        order: 1,
        coverPhoto: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-103-4',
            name: 'Charles Bridge & Old Town Square Walk',
            description: 'Dawn stroll past Gothic statues followed by the Astronomical Clock hourly procession.',
            category: 'sightseeing',
            startTime: '08:00',
            endTime: '10:30',
            durationHours: 2.5,
            cost: 0,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-15',
            imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-103-5',
            name: 'Prague Castle & St. Vitus Cathedral Tour',
            description: 'Explore the sprawling castle courtyards, Gothic nave, and the colorful Golden Lane artisan cottages.',
            category: 'culture',
            startTime: '11:00',
            endTime: '14:30',
            durationHours: 3.5,
            cost: 22,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-15',
            imageUrl: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-103-6',
            name: 'Medieval Underground Tavern & Pilsner Feast',
            description: 'Roast duck, homemade dumplings, and fresh unpasteurized Pilsner Urquell by candlelight.',
            category: 'food',
            startTime: '18:30',
            endTime: '21:00',
            durationHours: 2.5,
            cost: 40,
            currency: 'USD',
            rating: 4.7,
            cityId: 'city-15',
            imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
    ],
  },

  // ── Trip 4: Southeast Asia Island Odyssey ──────────────────────────────────
  {
    id: 'trip-104',
    name: 'Southeast Asia Island Odyssey',
    description: 'Emerald jungle terraces, crystal reef diving, street food night markets, and sky gardens.',
    coverPhoto: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    budget: 2900,
    budgetBreakdown: { transport: 650, stay: 1100, activities: 550, meals: 400, misc: 200 },
    isPublic: true,
    status: 'upcoming',
    createdAt: '2026-08-10T14:00:00Z',
    updatedAt: '2026-08-22T09:15:00Z',
    userId: 'user-1',
    shareSlug: 'southeast-asia-island-odyssey-2027',
    tags: ['beach', 'nature', 'adventure'],
    stops: [
      {
        id: 'stop-104-a',
        cityId: 'city-16',
        city: 'Singapore',
        country: 'Singapore',
        countryCode: 'SG',
        startDate: '2027-01-10',
        endDate: '2027-01-14',
        order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-104-1',
            name: 'Gardens by the Bay Flower Dome & Cloud Forest',
            description: 'Stand beneath the indoor 35-meter waterfall surrounded by exotic plants from tropical highlands.',
            category: 'sightseeing',
            startTime: '09:30',
            endTime: '12:30',
            durationHours: 3,
            cost: 32,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-16',
            imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-104-2',
            name: 'Lau Pa Sat Satay Street & Hawker Tasting',
            description: 'Feast on Hainanese chicken rice, chili crab bao, char kway teow, and charcoal grilled satay skewers.',
            category: 'food',
            startTime: '13:00',
            endTime: '15:00',
            durationHours: 2,
            cost: 20,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-16',
            imageUrl: 'https://images.unsplash.com/photo-1506354666786-959d6d497f1a?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-104-3',
            name: 'Marina Bay Sands SkyPark Observation Deck',
            description: 'Gaze over Singapore strait and futuristic skyline from the 57th floor cantilevering deck.',
            category: 'sightseeing',
            startTime: '17:30',
            endTime: '19:30',
            durationHours: 2,
            cost: 26,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-16',
            imageUrl: 'https://images.unsplash.com/photo-1508964942454-1a56651d54ac?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
      {
        id: 'stop-104-b',
        cityId: 'city-3',
        city: 'Bali',
        country: 'Indonesia',
        countryCode: 'ID',
        startDate: '2027-01-14',
        endDate: '2027-01-19',
        order: 1,
        coverPhoto: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-104-4',
            name: 'Tegalalang Rice Terrace Sunrise Trek',
            description: 'Early walk through cascading emerald stepped valleys with palm trees illuminated in morning mist.',
            category: 'adventure',
            startTime: '06:00',
            endTime: '08:30',
            durationHours: 2.5,
            cost: 10,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-3',
            imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-104-5',
            name: 'Ubud Sacred Monkey Forest Sanctuary',
            description: 'Walk ancient moss-covered stone bridges and ancient banyan trees inhabited by hundreds of long-tailed macaques.',
            category: 'sightseeing',
            startTime: '10:00',
            endTime: '12:00',
            durationHours: 2,
            cost: 8,
            currency: 'USD',
            rating: 4.7,
            cityId: 'city-3',
            imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-104-6',
            name: 'Tanah Lot Temple Ocean Sunset',
            description: 'Watch waves crash against the offshore rock temple as the sun dips into the Indian Ocean horizon.',
            category: 'culture',
            startTime: '16:30',
            endTime: '18:45',
            durationHours: 2.25,
            cost: 5,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-3',
            imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
    ],
  },

  // ── Trip 5: Alpine Wonders & Swiss Lakes ────────────────────────────────────
  {
    id: 'trip-105',
    name: 'Alpine Wonders & Swiss Lakes',
    description: 'Crisp glacier air, iconic cogwheel alpine railways, fondue chalets, and mirror-still mountain lakes.',
    coverPhoto: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80',
    budget: 4800,
    budgetBreakdown: { transport: 1300, stay: 1900, activities: 750, meals: 650, misc: 200 },
    isPublic: true,
    status: 'upcoming',
    createdAt: '2026-08-01T08:30:00Z',
    updatedAt: '2026-08-20T16:00:00Z',
    userId: 'user-1',
    shareSlug: 'alpine-wonders-swiss-2026',
    tags: ['nature', 'winter', 'adventure'],
    stops: [
      {
        id: 'stop-105-a',
        cityId: 'city-2',
        city: 'Paris',
        country: 'France',
        countryCode: 'FR',
        startDate: '2026-12-18',
        endDate: '2026-12-22',
        order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-105-1',
            name: 'Croissant Baking Masterclass in Le Marais',
            description: 'Learn French lamination techniques and bake flaky butter croissants with a master artisan pastry chef.',
            category: 'food',
            startTime: '08:30',
            endTime: '11:00',
            durationHours: 2.5,
            cost: 85,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-2',
            imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-105-2',
            name: 'Louvre Museum Guided Masterpiece Tour',
            description: 'Skip-the-line journey through the Denon wing featuring the Mona Lisa, Winged Victory, and Venus de Milo.',
            category: 'culture',
            startTime: '11:30',
            endTime: '15:00',
            durationHours: 3.5,
            cost: 65,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-2',
            imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-105-3',
            name: 'Eiffel Tower Summit & Illumination Walk',
            description: 'Ascend to the top level for 360-degree city views followed by evening sparkle lights on the Champ de Mars.',
            category: 'sightseeing',
            startTime: '18:00',
            endTime: '20:30',
            durationHours: 2.5,
            cost: 38,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-2',
            imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
      {
        id: 'stop-105-b',
        cityId: 'city-5',
        city: 'Barcelona',
        country: 'Spain',
        countryCode: 'ES',
        startDate: '2026-12-22',
        endDate: '2026-12-27',
        order: 1,
        coverPhoto: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-105-4',
            name: 'Sagrada Família Towers & Basilica Tour',
            description: 'Marvel at Antoni Gaudí forest of columns and stained glass windows casting vivid rainbow prisms.',
            category: 'culture',
            startTime: '09:00',
            endTime: '11:30',
            durationHours: 2.5,
            cost: 40,
            currency: 'USD',
            rating: 5.0,
            cityId: 'city-5',
            imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-105-5',
            name: 'Park Güell Monumental Zone Stroll',
            description: 'Vibrant mosaic salamanders, serpentine stone benches, and panoramic Mediterranean vistas.',
            category: 'sightseeing',
            startTime: '13:00',
            endTime: '15:30',
            durationHours: 2.5,
            cost: 14,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-5',
            imageUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-105-6',
            name: 'El Born Tapas & Vermouth Evening',
            description: 'Ibérico ham, pimientos de padrón, patatas bravas, and artisanal Catalan vermouth in historic bodegas.',
            category: 'food',
            startTime: '19:00',
            endTime: '22:00',
            durationHours: 3,
            cost: 55,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-5',
            imageUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
    ],
  },

  // ── Trip 6: Arabian Sands & Futuristic Skylines ───────────────────────────
  {
    id: 'trip-106',
    name: 'Arabian Sands & Futuristic Skylines',
    description: 'Golden desert dune safaris, starlit Arabian dinners, and cutting-edge architectural marvels.',
    coverPhoto: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
    budget: 3600,
    budgetBreakdown: { transport: 800, stay: 1400, activities: 700, meals: 500, misc: 200 },
    isPublic: true,
    status: 'upcoming',
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-08-22T07:30:00Z',
    userId: 'user-1',
    shareSlug: 'arabian-sands-dubai-2027',
    tags: ['luxury', 'adventure', 'sightseeing'],
    stops: [
      {
        id: 'stop-106-a',
        cityId: 'city-6',
        city: 'Dubai',
        country: 'United Arab Emirates',
        countryCode: 'AE',
        startDate: '2027-02-05',
        endDate: '2027-02-10',
        order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-106-1',
            name: 'Dubai Miracle Garden Morning Walk',
            description: 'Stroll through over 150 million blooming flowers crafted into intricate sculptures and arches.',
            category: 'sightseeing',
            startTime: '09:00',
            endTime: '11:30',
            durationHours: 2.5,
            cost: 25,
            currency: 'USD',
            rating: 4.7,
            cityId: 'city-6',
            imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-106-2',
            name: 'Desert 4x4 Dune Bashing & Bedouin BBQ',
            description: 'Thrilling sandboarding, camel rides at golden sunset, and traditional belly dance show under the desert stars.',
            category: 'adventure',
            startTime: '14:30',
            endTime: '21:00',
            durationHours: 6.5,
            cost: 95,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-6',
            imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-106-3',
            name: 'Burj Khalifa Level 148 Sky Lounge',
            description: 'High-altitude panoramic views from the world tallest outdoor observation deck with luxury dates and Arabic coffee.',
            category: 'sightseeing',
            startTime: '21:30',
            endTime: '23:00',
            durationHours: 1.5,
            cost: 115,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-6',
            imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
      {
        id: 'stop-106-b',
        cityId: 'city-17',
        city: 'Istanbul',
        country: 'Turkey',
        countryCode: 'TR',
        startDate: '2027-02-10',
        endDate: '2027-02-15',
        order: 1,
        coverPhoto: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-106-4',
            name: 'Hagia Sophia & Blue Mosque Exploration',
            description: 'Marvel at 6th-century Byzantine mosaics and the grand domes of Sultanahmet.',
            category: 'culture',
            startTime: '09:00',
            endTime: '12:00',
            durationHours: 3,
            cost: 30,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-17',
            imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-106-5',
            name: 'Grand Bazaar Spices & Ottoman Delights Tour',
            description: 'Navigate the labyrinth of 4,000 stalls tasting Turkish delight, baklava, and sumac roasted pistachios.',
            category: 'shopping',
            startTime: '13:00',
            endTime: '15:30',
            durationHours: 2.5,
            cost: 20,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-17',
            imageUrl: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-106-6',
            name: 'Bosphorus Sunset Yacht Cruise',
            description: 'Sail between Europe and Asia past illuminated Ottoman palaces and historic waterfront wooden mansions.',
            category: 'sightseeing',
            startTime: '17:00',
            endTime: '19:30',
            durationHours: 2.5,
            cost: 45,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-17',
            imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
    ],
  },

  // ── Trip 7: American Coast & Broadway Lights ───────────────────────────────
  {
    id: 'trip-107',
    name: 'American Coast & Broadway Lights',
    description: 'Manhattan iconic skyline, Broadway theater magic, Central Park bike trails, and coastal charm.',
    coverPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=80',
    budget: 4500,
    budgetBreakdown: { transport: 900, stay: 1800, activities: 900, meals: 650, misc: 250 },
    isPublic: true,
    status: 'upcoming',
    createdAt: '2026-08-14T15:00:00Z',
    updatedAt: '2026-08-22T06:00:00Z',
    userId: 'user-1',
    shareSlug: 'american-coast-broadway-2027',
    tags: ['city', 'culture', 'entertainment'],
    stops: [
      {
        id: 'stop-107-a',
        cityId: 'city-4',
        city: 'New York',
        country: 'United States',
        countryCode: 'US',
        startDate: '2027-04-08',
        endDate: '2027-04-14',
        order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-107-1',
            name: 'Central Park Scenic Bicycle Loop',
            description: 'Cycle past Bethesda Terrace, Strawberry Fields, Bow Bridge, and the Jacqueline Kennedy Onassis Reservoir.',
            category: 'adventure',
            startTime: '09:00',
            endTime: '11:30',
            durationHours: 2.5,
            cost: 25,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-4',
            imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-107-2',
            name: 'The Metropolitan Museum of Art Highlights',
            description: 'Explore the Temple of Dendur, Greek sculptures, European paintings, and the rooftop terrace sculpture garden.',
            category: 'culture',
            startTime: '12:30',
            endTime: '15:30',
            durationHours: 3,
            cost: 30,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-4',
            imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-107-3',
            name: 'High Line Park & Chelsea Market Bites',
            description: 'Elevated park stroll with views of Hudson Yards followed by artisan tacos and Maine lobster rolls.',
            category: 'food',
            startTime: '16:00',
            endTime: '18:30',
            durationHours: 2.5,
            cost: 35,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-4',
            imageUrl: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-107-4',
            name: 'Broadway Evening Musical Show',
            description: 'Prime orchestra seats to an award-winning musical on the Great White Way in Times Square.',
            category: 'culture',
            startTime: '20:00',
            endTime: '22:45',
            durationHours: 2.75,
            cost: 140,
            currency: 'USD',
            rating: 5.0,
            cityId: 'city-4',
            imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
      {
        id: 'stop-107-b',
        cityId: 'city-10',
        city: 'Sydney',
        country: 'Australia',
        countryCode: 'AU',
        startDate: '2027-04-14',
        endDate: '2027-04-19',
        order: 1,
        coverPhoto: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-107-5',
            name: 'Sydney Harbour BridgeClimb Dawn Experience',
            description: 'Scale the iconic steel arches at sunrise for 360-degree views over Sydney Harbour and the Opera House.',
            category: 'adventure',
            startTime: '06:00',
            endTime: '09:30',
            durationHours: 3.5,
            cost: 195,
            currency: 'USD',
            rating: 5.0,
            cityId: 'city-10',
            imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-107-6',
            name: 'Sydney Opera House Behind-the-Scenes Tour',
            description: 'Explore the concert halls and acoustic engineering beneath Jørn Utzon world-famous ceramic sail roofs.',
            category: 'culture',
            startTime: '11:00',
            endTime: '13:00',
            durationHours: 2,
            cost: 42,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-10',
            imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-107-7',
            name: 'Bondi to Coogee Coastal Cliff Walk',
            description: 'Stroll along dramatic ocean headlands, passing Tamarama and Bronte beaches, stopping for fish & chips.',
            category: 'sightseeing',
            startTime: '14:30',
            endTime: '17:30',
            durationHours: 3,
            cost: 18,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-10',
            imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
    ],
  },

  // ── Trip 8: Tropical Paradise & Coral Lagoons ──────────────────────────────
  {
    id: 'trip-108',
    name: 'Tropical Paradise & Coral Lagoons',
    description: 'Overwater bungalows, pristine turquoise atolls, manta ray snorkeling, and Cape Town mountain vistas.',
    coverPhoto: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1200&q=80',
    budget: 6200,
    budgetBreakdown: { transport: 1500, stay: 2800, activities: 950, meals: 700, misc: 250 },
    isPublic: true,
    status: 'upcoming',
    createdAt: '2026-08-16T12:00:00Z',
    updatedAt: '2026-08-22T05:00:00Z',
    userId: 'user-1',
    shareSlug: 'tropical-paradise-maldives-2027',
    tags: ['luxury', 'beach', 'nature'],
    stops: [
      {
        id: 'stop-108-a',
        cityId: 'city-20',
        city: 'Maldives',
        country: 'Maldives',
        countryCode: 'MV',
        startDate: '2027-11-04',
        endDate: '2027-11-10',
        order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-108-1',
            name: 'House Reef Guided Coral Snorkeling',
            description: 'Swim alongside hawksbill sea turtles, reef sharks, and schools of blue surgeonfish in translucent water.',
            category: 'adventure',
            startTime: '08:30',
            endTime: '11:00',
            durationHours: 2.5,
            cost: 65,
            currency: 'USD',
            rating: 5.0,
            cityId: 'city-20',
            imageUrl: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-108-2',
            name: 'Overwater Sunset Dolphin Cruise',
            description: 'Sail in a traditional wooden dhoni watching pods of spinner dolphins jumping in the golden sun rays.',
            category: 'sightseeing',
            startTime: '16:30',
            endTime: '18:45',
            durationHours: 2.25,
            cost: 85,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-20',
            imageUrl: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-108-3',
            name: 'Underwater Restaurant Candlelight Dinner',
            description: 'Dine 5 meters below sea level surrounded by panoramic acrylic views of coral gardens and marine life.',
            category: 'food',
            startTime: '19:30',
            endTime: '22:00',
            durationHours: 2.5,
            cost: 220,
            currency: 'USD',
            rating: 5.0,
            cityId: 'city-20',
            imageUrl: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
      {
        id: 'stop-108-b',
        cityId: 'city-14',
        city: 'Cape Town',
        country: 'South Africa',
        countryCode: 'ZA',
        startDate: '2027-11-10',
        endDate: '2027-11-16',
        order: 1,
        coverPhoto: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'act-108-4',
            name: 'Table Mountain Rotating Cable Car',
            description: 'Ascend one of the New 7 Wonders of Nature for sweeping views across the Atlantic Seaboard and City Bowl.',
            category: 'sightseeing',
            startTime: '09:00',
            endTime: '12:00',
            durationHours: 3,
            cost: 32,
            currency: 'USD',
            rating: 4.9,
            cityId: 'city-14',
            imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-108-5',
            name: 'Boulders Beach African Penguin Colony',
            description: 'Walk the boardwalks above sheltered coves to watch hundreds of wild African penguins swimming and nesting.',
            category: 'nature' as any,
            startTime: '13:30',
            endTime: '16:00',
            durationHours: 2.5,
            cost: 15,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-14',
            imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=400&q=80',
          },
          {
            id: 'act-108-6',
            name: 'V&A Waterfront Seafood & Marimba Evening',
            description: 'Fresh grilled kingklip, calamari, and Cape Malay curries accompanied by live acoustic marimba music.',
            category: 'food',
            startTime: '18:30',
            endTime: '21:00',
            durationHours: 2.5,
            cost: 45,
            currency: 'USD',
            rating: 4.8,
            cityId: 'city-14',
            imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=400&q=80',
          },
        ],
      },
    ],
  },
];
