import type { Activity, CityMeta, CityStop, Trip, User, AdminUser, AnalyticsStat } from '@/types';

// ─── Cities ───────────────────────────────────────────────────────────────────

export const mockCities: CityMeta[] = [
  {
    id: 'city-1', name: 'Tokyo', country: 'Japan', countryCode: 'JP', region: 'Asia',
    costIndex: 7, costTier: 'mid-range', popularityScore: 98, timezone: 'Asia/Tokyo',
    coverPhoto: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
    description: 'A dazzling megacity blending ultra-modern technology with ancient temples and world-class cuisine.',
    bestTimeToVisit: 'March–May, Sep–Nov', avgDailyCostUSD: 120,
    topActivities: ['Shibuya Crossing', 'Senso-ji Temple', 'Tsukiji Market', 'Akihabara'],
  },
  {
    id: 'city-2', name: 'Paris', country: 'France', countryCode: 'FR', region: 'Europe',
    costIndex: 8, costTier: 'luxury', popularityScore: 97, timezone: 'Europe/Paris',
    coverPhoto: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=80',
    description: 'The City of Light — timeless romance, haute cuisine, and iconic art at every turn.',
    bestTimeToVisit: 'Apr–Jun, Sep–Oct', avgDailyCostUSD: 160,
    topActivities: ['Eiffel Tower', 'Louvre Museum', 'Montmartre', 'Seine River Cruise'],
  },
  {
    id: 'city-3', name: 'Bali', country: 'Indonesia', countryCode: 'ID', region: 'Asia',
    costIndex: 3, costTier: 'budget', popularityScore: 92, timezone: 'Asia/Makassar',
    coverPhoto: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    description: 'Tropical paradise of rice terraces, spiritual temples, surf beaches, and vibrant nightlife.',
    bestTimeToVisit: 'Apr–Oct', avgDailyCostUSD: 50,
    topActivities: ['Ubud Rice Terraces', 'Tanah Lot Temple', 'Kuta Beach', 'Monkey Forest'],
  },
  {
    id: 'city-4', name: 'New York', country: 'USA', countryCode: 'US', region: 'Americas',
    costIndex: 9, costTier: 'luxury', popularityScore: 96, timezone: 'America/New_York',
    coverPhoto: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80',
    description: 'The city that never sleeps — skyscrapers, Broadway, world-class museums, and infinite food.',
    bestTimeToVisit: 'Sep–Nov, Mar–May', avgDailyCostUSD: 200,
    topActivities: ['Central Park', 'Times Square', 'Brooklyn Bridge', 'MoMA'],
  },
  {
    id: 'city-5', name: 'Barcelona', country: 'Spain', countryCode: 'ES', region: 'Europe',
    costIndex: 6, costTier: 'mid-range', popularityScore: 93, timezone: 'Europe/Madrid',
    coverPhoto: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80',
    description: 'Gaudí\'s dreamscapes, tapas culture, golden beaches, and electric nightlife in one city.',
    bestTimeToVisit: 'May–Jun, Sep', avgDailyCostUSD: 110,
    topActivities: ['Sagrada Família', 'Park Güell', 'La Rambla', 'Gothic Quarter'],
  },
  {
    id: 'city-6', name: 'Dubai', country: 'UAE', countryCode: 'AE', region: 'Middle East',
    costIndex: 8, costTier: 'luxury', popularityScore: 90, timezone: 'Asia/Dubai',
    coverPhoto: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
    description: 'Futuristic skyline rising from the desert — luxury shopping, record-breaking towers, and desert safaris.',
    bestTimeToVisit: 'Nov–Mar', avgDailyCostUSD: 180,
    topActivities: ['Burj Khalifa', 'Dubai Mall', 'Desert Safari', 'Palm Jumeirah'],
  },
  {
    id: 'city-7', name: 'Amsterdam', country: 'Netherlands', countryCode: 'NL', region: 'Europe',
    costIndex: 7, costTier: 'mid-range', popularityScore: 88, timezone: 'Europe/Amsterdam',
    coverPhoto: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80',
    description: 'Canal-laced city of bicycles, world-class art, and a famously liberal culture.',
    bestTimeToVisit: 'Apr–May, Sep', avgDailyCostUSD: 130,
    topActivities: ['Rijksmuseum', 'Anne Frank House', 'Canal Cruise', 'Vondelpark'],
  },
  {
    id: 'city-8', name: 'Bangkok', country: 'Thailand', countryCode: 'TH', region: 'Asia',
    costIndex: 3, costTier: 'budget', popularityScore: 91, timezone: 'Asia/Bangkok',
    coverPhoto: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80',
    description: 'Chaotic, vibrant, and endlessly fascinating — street food heaven with ornate temples.',
    bestTimeToVisit: 'Nov–Feb', avgDailyCostUSD: 45,
    topActivities: ['Grand Palace', 'Wat Pho', 'Chatuchak Market', 'Chao Phraya River'],
  },
  {
    id: 'city-9', name: 'Rome', country: 'Italy', countryCode: 'IT', region: 'Europe',
    costIndex: 6, costTier: 'mid-range', popularityScore: 95, timezone: 'Europe/Rome',
    coverPhoto: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
    description: 'The Eternal City — layers of millennia-old history beside gelaterias and piazzas.',
    bestTimeToVisit: 'Apr–Jun, Sep–Oct', avgDailyCostUSD: 115,
    topActivities: ['Colosseum', 'Vatican', 'Trevi Fountain', 'Roman Forum'],
  },
  {
    id: 'city-10', name: 'Sydney', country: 'Australia', countryCode: 'AU', region: 'Oceania',
    costIndex: 8, costTier: 'luxury', popularityScore: 89, timezone: 'Australia/Sydney',
    coverPhoto: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&q=80',
    description: 'Iconic harbour city with world-famous Opera House, golden beaches, and laid-back culture.',
    bestTimeToVisit: 'Sep–Nov, Mar–May', avgDailyCostUSD: 175,
    topActivities: ['Opera House', 'Bondi Beach', 'Harbour Bridge', 'Blue Mountains'],
  },
  {
    id: 'city-11', name: 'Kyoto', country: 'Japan', countryCode: 'JP', region: 'Asia',
    costIndex: 6, costTier: 'mid-range', popularityScore: 87, timezone: 'Asia/Tokyo',
    coverPhoto: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    description: 'Japan\'s ancient capital — thousands of shrines, geishas, and bamboo groves.',
    bestTimeToVisit: 'Mar–May, Oct–Nov', avgDailyCostUSD: 100,
    topActivities: ['Fushimi Inari', 'Arashiyama Bamboo', 'Kinkaku-ji', 'Gion District'],
  },
  {
    id: 'city-12', name: 'Marrakech', country: 'Morocco', countryCode: 'MA', region: 'Africa',
    costIndex: 3, costTier: 'budget', popularityScore: 84, timezone: 'Africa/Casablanca',
    coverPhoto: 'https://images.unsplash.com/photo-1539020140153-e479b8f22986?w=800&q=80',
    description: 'Sensory overload of souks, riads, spice markets, and Saharan sunsets.',
    bestTimeToVisit: 'Mar–May, Sep–Nov', avgDailyCostUSD: 40,
    topActivities: ['Djemaa el-Fna', 'Bahia Palace', 'Majorelle Garden', 'Atlas Mountains'],
  },
  {
    id: 'city-13', name: 'Santorini', country: 'Greece', countryCode: 'GR', region: 'Europe',
    costIndex: 7, costTier: 'mid-range', popularityScore: 90, timezone: 'Europe/Athens',
    coverPhoto: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    description: 'Iconic white-washed villages perched on volcanic cliffs above the electric blue Aegean.',
    bestTimeToVisit: 'Apr–Jun, Sep–Oct', avgDailyCostUSD: 140,
    topActivities: ['Oia Sunset', 'Akrotiri Ruins', 'Black Beach', 'Wine Tasting'],
  },
  {
    id: 'city-14', name: 'Cape Town', country: 'South Africa', countryCode: 'ZA', region: 'Africa',
    costIndex: 4, costTier: 'budget', popularityScore: 82, timezone: 'Africa/Johannesburg',
    coverPhoto: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80',
    description: 'Dramatic Table Mountain backdrop, world-class wine, and vibrant multicultural energy.',
    bestTimeToVisit: 'Nov–Mar', avgDailyCostUSD: 65,
    topActivities: ['Table Mountain', 'Cape of Good Hope', 'V&A Waterfront', 'Robben Island'],
  },
  {
    id: 'city-15', name: 'Prague', country: 'Czech Republic', countryCode: 'CZ', region: 'Europe',
    costIndex: 4, costTier: 'budget', popularityScore: 86, timezone: 'Europe/Prague',
    coverPhoto: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&q=80',
    description: 'Fairy-tale Gothic architecture, cobblestone squares, and legendary Czech beer culture.',
    bestTimeToVisit: 'Apr–Jun, Sep–Oct', avgDailyCostUSD: 70,
    topActivities: ['Charles Bridge', 'Old Town Square', 'Prague Castle', 'Kafka Museum'],
  },
  {
    id: 'city-16', name: 'Singapore', country: 'Singapore', countryCode: 'SG', region: 'Asia',
    costIndex: 8, costTier: 'luxury', popularityScore: 88, timezone: 'Asia/Singapore',
    coverPhoto: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80',
    description: 'Futuristic garden city of superlative architecture, hawker centres, and multicultural harmony.',
    bestTimeToVisit: 'Feb–Apr', avgDailyCostUSD: 155,
    topActivities: ['Gardens by the Bay', 'Marina Bay Sands', 'Hawker Centres', 'Sentosa Island'],
  },
  {
    id: 'city-17', name: 'Istanbul', country: 'Turkey', countryCode: 'TR', region: 'Middle East',
    costIndex: 4, costTier: 'budget', popularityScore: 85, timezone: 'Europe/Istanbul',
    coverPhoto: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80',
    description: 'Where East meets West — minarets, bazaars, Bosphorus cruises, and exceptional food.',
    bestTimeToVisit: 'Apr–May, Sep–Oct', avgDailyCostUSD: 60,
    topActivities: ['Hagia Sophia', 'Grand Bazaar', 'Bosphorus Cruise', 'Topkapi Palace'],
  },
  {
    id: 'city-18', name: 'Lisbon', country: 'Portugal', countryCode: 'PT', region: 'Europe',
    costIndex: 5, costTier: 'mid-range', popularityScore: 83, timezone: 'Europe/Lisbon',
    coverPhoto: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
    description: 'Hilly, sun-drenched city of fado music, pastel de nata, and extraordinary Atlantic views.',
    bestTimeToVisit: 'Mar–May, Sep–Oct', avgDailyCostUSD: 85,
    topActivities: ['Belém Tower', 'Alfama District', 'Sintra', 'Tram 28'],
  },
  {
    id: 'city-19', name: 'Rio de Janeiro', country: 'Brazil', countryCode: 'BR', region: 'Americas',
    costIndex: 4, costTier: 'budget', popularityScore: 81, timezone: 'America/Sao_Paulo',
    coverPhoto: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80',
    description: 'Carnival, Christ the Redeemer, Copacabana, and samba — Brazil\'s soul in one city.',
    bestTimeToVisit: 'Dec–Mar, Jun–Aug', avgDailyCostUSD: 70,
    topActivities: ['Christ the Redeemer', 'Copacabana Beach', 'Sugarloaf Mountain', 'Lapa Arches'],
  },
  {
    id: 'city-20', name: 'Maldives', country: 'Maldives', countryCode: 'MV', region: 'Asia',
    costIndex: 9, costTier: 'luxury', popularityScore: 85, timezone: 'Indian/Maldives',
    coverPhoto: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80',
    description: 'Crystalline waters, overwater bungalows, and the world\'s finest coral reefs.',
    bestTimeToVisit: 'Nov–Apr', avgDailyCostUSD: 300,
    topActivities: ['Snorkeling', 'Overwater Bungalow Stay', 'Dolphin Watching', 'Whale Shark Dive'],
  },
];

// ─── Activities ───────────────────────────────────────────────────────────────

export const mockActivities: Activity[] = [
  { id: 'act-1', name: 'Shibuya Crossing Walk', description: 'Experience the world\'s busiest pedestrian crossing at rush hour.', category: 'sightseeing', time: '18:00', durationHours: 1, cost: 0, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=400&q=80', rating: 4.8, cityId: 'city-1' },
  { id: 'act-2', name: 'Senso-ji Temple Visit', description: 'Tokyo\'s oldest and most significant Buddhist temple.', category: 'culture', time: '09:00', durationHours: 2, cost: 5, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=400&q=80', rating: 4.9, cityId: 'city-1' },
  { id: 'act-3', name: 'Tsukiji Outer Market Food Tour', description: 'Sample fresh sushi, tamagoyaki, and street snacks.', category: 'food', time: '08:00', durationHours: 2, cost: 40, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1568454537842-d933259bb258?w=400&q=80', rating: 4.7, cityId: 'city-1' },
  { id: 'act-4', name: 'Eiffel Tower Skip-the-Line', description: 'Ascend Paris\'s most iconic monument for panoramic views.', category: 'sightseeing', time: '10:00', durationHours: 2, cost: 28, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=400&q=80', rating: 4.9, cityId: 'city-2' },
  { id: 'act-5', name: 'Louvre Museum Guided Tour', description: 'Discover the Mona Lisa and thousands of masterpieces.', category: 'culture', time: '09:30', durationHours: 4, cost: 55, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=400&q=80', rating: 4.8, cityId: 'city-2' },
  { id: 'act-6', name: 'Ubud Rice Terrace Trek', description: 'Hike through emerald green Tegalalang rice paddies at sunrise.', category: 'adventure', time: '06:00', durationHours: 3, cost: 15, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400&q=80', rating: 4.8, cityId: 'city-3' },
  { id: 'act-7', name: 'Tanah Lot Sunset Temple', description: 'Witness the dramatic sea temple at golden hour.', category: 'culture', time: '16:30', durationHours: 2, cost: 5, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=400&q=80', rating: 4.7, cityId: 'city-3' },
  { id: 'act-8', name: 'Central Park Bike Ride', description: 'Cycle through 843 acres of urban oasis in Manhattan.', category: 'adventure', time: '10:00', durationHours: 2, cost: 20, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80', rating: 4.6, cityId: 'city-4' },
  { id: 'act-9', name: 'Broadway Show', description: 'Catch a world-class musical on the Great White Way.', category: 'culture', time: '20:00', durationHours: 3, cost: 120, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80', rating: 4.9, cityId: 'city-4' },
  { id: 'act-10', name: 'Sagrada Família Tour', description: 'Marvel at Gaudí\'s unfinished masterpiece and its soaring spires.', category: 'culture', time: '10:00', durationHours: 2, cost: 35, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=400&q=80', rating: 4.9, cityId: 'city-5' },
  { id: 'act-11', name: 'Burj Khalifa Observation Deck', description: 'Stand atop the world\'s tallest building at 828m.', category: 'sightseeing', time: '19:00', durationHours: 2, cost: 45, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=400&q=80', rating: 4.8, cityId: 'city-6' },
  { id: 'act-12', name: 'Desert Safari & BBQ Dinner', description: 'Dune bashing, camel rides, belly dancing, and starlit BBQ.', category: 'adventure', time: '15:00', durationHours: 6, cost: 85, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400&q=80', rating: 4.7, cityId: 'city-6' },
  { id: 'act-13', name: 'Rijksmuseum Visit', description: 'Home to Rembrandt, Vermeer, and Dutch Golden Age masterpieces.', category: 'culture', time: '09:00', durationHours: 3, cost: 22, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=400&q=80', rating: 4.8, cityId: 'city-7' },
  { id: 'act-14', name: 'Fushimi Inari Shrine Hike', description: 'Walk through thousands of vermillion torii gates up the mountain.', category: 'sightseeing', time: '07:00', durationHours: 3, cost: 0, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=400&q=80', rating: 4.9, cityId: 'city-11' },
  { id: 'act-15', name: 'Colosseum & Roman Forum', description: 'Step inside the ancient gladiatorial arena and walk the Forum.', category: 'culture', time: '09:00', durationHours: 3, cost: 32, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=400&q=80', rating: 4.9, cityId: 'city-9' },
  { id: 'act-16', name: 'Sydney Opera House Tour', description: 'Behind-the-scenes tour of the world\'s most recognizable building.', category: 'culture', time: '10:00', durationHours: 2, cost: 40, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=400&q=80', rating: 4.7, cityId: 'city-10' },
  { id: 'act-17', name: 'Santorini Sunset Cruise', description: 'Sail around the caldera and watch the legendary Oia sunset.', category: 'sightseeing', time: '15:00', durationHours: 4, cost: 65, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=400&q=80', rating: 4.9, cityId: 'city-13' },
  { id: 'act-18', name: 'Table Mountain Cable Car', description: 'Ascend one of the New Seven Wonders of Nature for 360° views.', category: 'adventure', time: '10:00', durationHours: 3, cost: 28, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=400&q=80', rating: 4.8, cityId: 'city-14' },
  { id: 'act-19', name: 'Prague Castle Walk', description: 'Explore the largest ancient castle complex in the world.', category: 'culture', time: '09:00', durationHours: 3, cost: 18, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=400&q=80', rating: 4.7, cityId: 'city-15' },
  { id: 'act-20', name: 'Singapore Hawker Centre Crawl', description: 'Eat your way through Lau Pa Sat tasting laksa, char kway teow & more.', category: 'food', time: '12:00', durationHours: 2, cost: 20, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=400&q=80', rating: 4.8, cityId: 'city-16' },
  { id: 'act-21', name: 'Bosphorus Sunset Cruise', description: 'Glide between Europe and Asia on the legendary Bosphorus strait.', category: 'sightseeing', time: '17:00', durationHours: 2, cost: 25, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=400&q=80', rating: 4.7, cityId: 'city-17' },
  { id: 'act-22', name: 'Maldives Snorkeling Adventure', description: 'Swim alongside manta rays and sea turtles in crystal lagoons.', category: 'adventure', time: '09:00', durationHours: 3, cost: 80, currency: 'USD', imageUrl: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=400&q=80', rating: 4.9, cityId: 'city-20' },
];

// ─── Mock Trips ───────────────────────────────────────────────────────────────

export const mockTrips: Trip[] = [
  {
    id: 'trip-1',
    name: 'Japan Highlights',
    description: 'An epic 2-week journey through Tokyo\'s neon districts and Kyoto\'s ancient temples.',
    coverPhoto: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80',
    status: 'upcoming',
    isPublic: true,
    shareSlug: 'japan-highlights-2024',
    budget: 3500,
    budgetBreakdown: { transport: 800, stay: 1200, activities: 600, meals: 500, misc: 400 },
    userId: 'user-1',
    createdAt: '2024-11-01T10:00:00Z',
    updatedAt: '2024-11-15T14:00:00Z',
    tags: ['culture', 'food', 'adventure'],
    stops: [
      {
        id: 'stop-1a', cityId: 'city-1', city: 'Tokyo', country: 'Japan', countryCode: 'JP',
        startDate: '2024-12-20', endDate: '2024-12-25', order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
        activities: [mockActivities[0], mockActivities[1], mockActivities[2]],
      },
      {
        id: 'stop-1b', cityId: 'city-11', city: 'Kyoto', country: 'Japan', countryCode: 'JP',
        startDate: '2024-12-26', endDate: '2024-12-30', order: 1,
        coverPhoto: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
        activities: [mockActivities[13]],
      },
    ],
  },
  {
    id: 'trip-2',
    name: 'European Dream',
    description: 'Romance, art, and tapas across Paris, Barcelona, and Rome.',
    coverPhoto: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1200&q=80',
    status: 'draft',
    isPublic: false,
    shareSlug: 'european-dream-2025',
    budget: 5000,
    budgetBreakdown: { transport: 1200, stay: 1800, activities: 900, meals: 700, misc: 400 },
    userId: 'user-1',
    createdAt: '2024-10-15T08:00:00Z',
    updatedAt: '2024-11-10T11:00:00Z',
    tags: ['culture', 'romance', 'food'],
    stops: [
      {
        id: 'stop-2a', cityId: 'city-2', city: 'Paris', country: 'France', countryCode: 'FR',
        startDate: '2025-06-01', endDate: '2025-06-05', order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=80',
        activities: [mockActivities[3], mockActivities[4]],
      },
      {
        id: 'stop-2b', cityId: 'city-5', city: 'Barcelona', country: 'Spain', countryCode: 'ES',
        startDate: '2025-06-06', endDate: '2025-06-09', order: 1,
        coverPhoto: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80',
        activities: [mockActivities[9]],
      },
      {
        id: 'stop-2c', cityId: 'city-9', city: 'Rome', country: 'Italy', countryCode: 'IT',
        startDate: '2025-06-10', endDate: '2025-06-14', order: 2,
        coverPhoto: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
        activities: [mockActivities[14]],
      },
    ],
  },
  {
    id: 'trip-3',
    name: 'Southeast Asia Adventure',
    description: 'Surf, temples, and street food from Bali to Bangkok.',
    coverPhoto: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=80',
    status: 'completed',
    isPublic: true,
    shareSlug: 'sea-adventure-2024',
    budget: 2000,
    budgetBreakdown: { transport: 400, stay: 600, activities: 450, meals: 350, misc: 200 },
    userId: 'user-1',
    createdAt: '2024-08-01T09:00:00Z',
    updatedAt: '2024-09-01T09:00:00Z',
    tags: ['adventure', 'budget', 'culture'],
    stops: [
      {
        id: 'stop-3a', cityId: 'city-3', city: 'Bali', country: 'Indonesia', countryCode: 'ID',
        startDate: '2024-09-10', endDate: '2024-09-15', order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
        activities: [mockActivities[5], mockActivities[6]],
      },
      {
        id: 'stop-3b', cityId: 'city-8', city: 'Bangkok', country: 'Thailand', countryCode: 'TH',
        startDate: '2024-09-16', endDate: '2024-09-20', order: 1,
        coverPhoto: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80',
        activities: [],
      },
    ],
  },
  {
    id: 'trip-4',
    name: 'Arabian Nights & Sunsets',
    description: 'Luxury desert escapes, futuristic skylines, and ancient bazaars.',
    coverPhoto: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80',
    status: 'upcoming',
    isPublic: true,
    shareSlug: 'arabian-nights-2025',
    budget: 4500,
    budgetBreakdown: { transport: 900, stay: 2000, activities: 800, meals: 500, misc: 300 },
    userId: 'user-1',
    createdAt: '2024-11-20T08:00:00Z',
    updatedAt: '2024-11-22T12:00:00Z',
    tags: ['luxury', 'culture', 'food'],
    stops: [
      {
        id: 'stop-4a', cityId: 'city-6', city: 'Dubai', country: 'UAE', countryCode: 'AE',
        startDate: '2025-02-01', endDate: '2025-02-05', order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
        activities: [mockActivities[10], mockActivities[11]],
      },
      {
        id: 'stop-4b', cityId: 'city-17', city: 'Istanbul', country: 'Turkey', countryCode: 'TR',
        startDate: '2025-02-06', endDate: '2025-02-10', order: 1,
        coverPhoto: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80',
        activities: [mockActivities[20]],
      },
    ],
  },
  {
    id: 'trip-5',
    name: 'Island Paradise — Maldives',
    description: 'Honeymoon overwater bungalows, world-class diving, and absolute serenity.',
    coverPhoto: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1200&q=80',
    status: 'draft',
    isPublic: false,
    shareSlug: 'maldives-paradise-2025',
    budget: 6000,
    budgetBreakdown: { transport: 1500, stay: 3000, activities: 800, meals: 500, misc: 200 },
    userId: 'user-1',
    createdAt: '2024-11-25T08:00:00Z',
    updatedAt: '2024-11-25T08:00:00Z',
    tags: ['luxury', 'honeymoon', 'adventure'],
    stops: [
      {
        id: 'stop-5a', cityId: 'city-20', city: 'Maldives', country: 'Maldives', countryCode: 'MV',
        startDate: '2025-04-15', endDate: '2025-04-22', order: 0,
        coverPhoto: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80',
        activities: [mockActivities[21]],
      },
    ],
  },
];

// ─── Mock User ────────────────────────────────────────────────────────────────

export const mockUser: User = {
  id: 'user-1',
  name: 'Alex Wanderer',
  email: 'alex@globetrotter.io',
  avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&q=80',
  language: 'English',
  savedDestinations: ['city-1', 'city-3', 'city-13', 'city-20'],
  tripsCount: 5,
  joinedAt: '2024-01-15T10:00:00Z',
};

// ─── Admin Mock Data ──────────────────────────────────────────────────────────

export const mockAnalyticsStats: AnalyticsStat[] = [
  { label: 'Total Users', value: 12840, change: 14.2, trend: 'up' },
  { label: 'Trips Created', value: 38920, change: 22.5, trend: 'up' },
  { label: 'Cities Explored', value: 184, change: 8.1, trend: 'up' },
  { label: 'Avg. Trip Duration', value: '11.4 days', change: -2.3, trend: 'down' },
  { label: 'Public Shares', value: 6210, change: 31.7, trend: 'up' },
  { label: 'Daily Active Users', value: 4290, change: 5.8, trend: 'up' },
];

export const mockAdminUsers: AdminUser[] = [
  { id: 'user-1', name: 'Alex Wanderer', email: 'alex@globe.io', tripsCount: 5, joinedAt: '2024-01-15T10:00:00Z', status: 'active' },
  { id: 'user-2', name: 'Priya Sharma', email: 'priya@globe.io', tripsCount: 12, joinedAt: '2024-02-20T08:00:00Z', status: 'active' },
  { id: 'user-3', name: 'Marco Rossi', email: 'marco@globe.io', tripsCount: 3, joinedAt: '2024-03-10T09:00:00Z', status: 'active' },
  { id: 'user-4', name: 'Yuna Kim', email: 'yuna@globe.io', tripsCount: 8, joinedAt: '2024-04-05T07:00:00Z', status: 'inactive' },
  { id: 'user-5', name: 'Carlos Rivera', email: 'carlos@globe.io', tripsCount: 1, joinedAt: '2024-05-12T11:00:00Z', status: 'active' },
];
